name: fire_walker
description: "Fire Walker-flutter"
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  get_it: ^7.7.0

  # Freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  # DB
  flutter_secure_storage: ^4.2.1

  # Social Login
  sign_in_with_apple: ^6.1.4
  kakao_flutter_sdk_user: ^1.9.5

  # Utils
  uuid: ^4.4.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_dotenv: ^5.1.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  dio: ^5.7.0
  flutter_launcher_icons: ^0.14.1
  rive: ^0.13.20
  flutter_svg: ^2.0.16
  syncfusion_flutter_gauges: ^27.2.5
  animated_digit: ^3.2.3
  url_launcher: ^6.3.1
  protoc_plugin: ^21.1.2
  grpc: ^4.0.1
  protobuf: ^3.1.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  firebase_messaging: ^15.1.6
  go_router: ^14.6.2
  introduction_screen: ^3.1.14

flutter:
  uses-material-design: true

  assets:
    - images/
#    - .env

flutter_launcher_icons:
  ios: true
  image_path_ios: "images/appstore.png"

  platforms:
    ios:
      minimum_os_version: 15.0
